"""empty message

Revision ID: 10cb37d5d071
Revises: 222f1f45b464
Create Date: 2024-03-26 14:59:57.467824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10cb37d5d071'
down_revision = '222f1f45b464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senior_citizen_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('senior_citizen_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('senior_citizen_id')
        batch_op.drop_column('senior_citizen_name')

    # ### end Alembic commands ###
